app:
  aquarium:
    size:
      type: ${AQUARIUM_SIZE_TYPE:LITER}

spring:
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
