INSERT INTO aquarium (id, size, glass_type, shape, max_Number_Of_Fish) VALUES
  (NEXTVAL('HIBERNATE_SEQUENCE'), 50, 'ACRYLIC', 'RECTANGLE_SQUARE', 2),
  (NEXTVAL('HIBERNATE_SEQUENCE'), 50, 'ACRYLIC', 'RECTANGLE_SQUARE', 3),
  (NEXTVAL('HIBERNATE_SEQUENCE'), 75, 'GLASS', 'CYLINDER', 5),
  (NEXTVAL('HIBERNATE_SEQUENCE'), 25, 'GLASS', 'BOW', 4),
  (NEXTVAL('HIBERNATE_SEQUENCE'), 80, 'GLASS', 'TRIANGLE', 3),
  (NEXTVAL('HIBERNATE_SEQUENCE'), 120, 'GLASS', 'WAVE', 15),
  (NEXTVAL('HIBERNATE_SEQUENCE'), 100, 'ACRYLIC', 'L_SHAPE', 10);


